//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pointage
    {
        public long PointageID { get; set; }
        public System.DateTime Jour { get; set; }
        public System.DateTime HeureEntree { get; set; }
        public Nullable<System.DateTime> HeureSortie { get; set; }
        public Nullable<long> EmployesID { get; set; }
        public string Imei_employe_entree { get; set; }
        public string Imei_employe_sortie { get; set; }
        public string Imei_verificateur_entree { get; set; }
        public string Imei_verificateur_sortie { get; set; }
        public string Application_id_entree { get; set; }
        public string Application_id_sortie { get; set; }
    
        public virtual Employes Employes { get; set; }
    }
}
